package policy

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// MaxGeneratedFiles bounds one render pass. The natural bound is the number
// of agent types a user actually runs, which is small, but "naturally small"
// is not a limit (constraint 10): a corrupt ledger or a future caller passing
// unfiltered input should hit a wall rather than fill a directory.
const MaxGeneratedFiles = 50

// generatedMarker identifies a file this package wrote. Render refuses to
// overwrite any existing file that does not carry it, which is what keeps a
// hand-written agent definition safe even if one is placed in the output
// directory by mistake (constraint 8).
const generatedMarker = "# Generated by loom. Do not edit: your changes will be overwritten."

// Rendered reports what one render pass did, so the caller can tell the user
// precisely rather than "done".
type Rendered struct {
	Written []string // absolute paths written this pass
	Skipped []string // agent types deliberately not rendered, with the reason
}

// Render writes one agent definition per decision that carries information
// worth pinning, into dir.
//
// A decision resolving to a shipped default is deliberately NOT rendered.
// Generating a file that restates a default produces material to review
// without adding anything to review it against, which is the exact trap
// constraint 10 names: answering "too much to keep track of" by making more
// to keep track of. Only a deliberate policy or trusted evidence earns a file.
//
// Files are overwritten, never appended, and never accumulate a second copy.
func Render(dir string, decisions []Decision) (Rendered, error) {
	var out Rendered

	var worth []Decision
	for _, d := range decisions {
		switch {
		case d.Source == SourceStored, d.TrustedEvidence():
			worth = append(worth, d)
		default:
			out.Skipped = append(out.Skipped, fmt.Sprintf("%s (%s, nothing to pin beyond the shipped default)", d.AgentType, d.Source))
		}
	}
	if len(worth) == 0 {
		return out, nil
	}
	if len(worth) > MaxGeneratedFiles {
		return out, fmt.Errorf("refusing to render %d files, limit is %d", len(worth), MaxGeneratedFiles)
	}

	if err := os.MkdirAll(dir, 0o700); err != nil {
		return out, err
	}

	for _, d := range worth {
		name, err := safeFileName(d.AgentType)
		if err != nil {
			return out, err
		}
		path := filepath.Join(dir, name)

		if err := refuseIfNotOurs(path); err != nil {
			return out, err
		}
		if err := os.WriteFile(path, []byte(renderOne(d)), 0o600); err != nil {
			return out, err
		}
		out.Written = append(out.Written, path)
	}
	return out, nil
}

// refuseIfNotOurs returns an error if path exists and was not written by
// Render. Loom overwriting something a human wrote is the failure the design
// doc calls out by name, so it is checked rather than assumed.
func refuseIfNotOurs(path string) error {
	existing, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !strings.Contains(string(existing), generatedMarker) {
		return fmt.Errorf("refusing to overwrite %s: it was not generated by loom", path)
	}
	return nil
}

// safeFileName rejects an agent type that would escape the output directory
// or produce a surprising filename. Agent types come from a .meta.json file
// Loom does not control, so this is untrusted input in exactly the sense
// constraint 9 means.
func safeFileName(agentType string) (string, error) {
	if agentType == "" {
		return "", fmt.Errorf("empty agent type")
	}
	if strings.ContainsAny(agentType, `/\:`) || strings.Contains(agentType, "..") {
		return "", fmt.Errorf("refusing to render agent type %q: unsafe as a filename", agentType)
	}
	return agentType + ".md", nil
}

// renderOne produces the file body. The frontmatter carries the pin; the
// prose below it carries the provenance, so someone reading the file in six
// months can tell what decided this and how much it rested on.
func renderOne(d Decision) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "name: %s\n", d.AgentType)
	fmt.Fprintf(&b, "description: %s agent, model pinned by loom.\n", d.AgentType)
	fmt.Fprintf(&b, "model: %s\n", d.Model)
	if d.Effort != "" {
		fmt.Fprintf(&b, "effort: %s\n", d.Effort)
	}
	b.WriteString("---\n\n")
	b.WriteString(generatedMarker + "\n\n")
	fmt.Fprintf(&b, "Pinned to `%s`", d.Model)
	if d.Effort != "" {
		fmt.Fprintf(&b, " at %s effort", d.Effort)
	}
	b.WriteString(".\n\n")
	fmt.Fprintf(&b, "- Source: %s\n", d.Source)
	if d.SampleSize > 0 {
		fmt.Fprintf(&b, "- Sample size: %d run(s)\n", d.SampleSize)
	}
	fmt.Fprintf(&b, "- Criteria version: %s\n", CriteriaVersion)
	fmt.Fprintf(&b, "- Basis: %s\n", d.Rationale)
	b.WriteString("\nLoom does not install this. Copy it where your client reads agent definitions\n")
	b.WriteString("if you want it to take effect, and note that reusing a built-in agent's name\n")
	b.WriteString("will shadow that agent.\n")
	return b.String()
}
